# Values used for the deployed application.
replicaCount: 1
service:
  name: publish-availability-monitor
envs:
  kafka_topic: "PreNativeCmsPublicationEvents"
  content_url: "/__document-store-api/content/"
  internal_components_url: "/__document-store-api/internalcomponents/"
  lists_url: "/__document-store-api/lists/"
  notifications_url: "/__notifications-rw/content/notifications?type=all"
  notifications_push_url: "/content/notifications-push?monitor=true"
  lists_notifications_url: "/__list-notifications-rw/lists/notifications"
  lists_notifications_push_url: "/lists/notifications-push?monitor=true"
  methode_article_validation_endpoint: "https://k8s-delivery-upp-eu.ft.com/__methode-article-mapper/map"
  methode_content_placeholder_mapper_endpoint: "https://k8s-delivery-upp-eu.ft.com/__methode-content-placeholder-mapper/map"
  methode_image_model_mapper_endpoint: "https://k8s-delivery-upp-eu.ft.com/__methode-image-model-mapper/map"
  methode_list_validation_endpoint: "https://k8s-delivery-upp-eu.ft.com/__methode-list-mapper/map"
  methode_article_internal_components_mapper_endpoint: "https://k8s-delivery-upp-eu.ft.com/__methode-article-internal-components-mapper/map"
  video_mapper_endpoint: "https://k8s-delivery-upp-eu.ft.com/__video-mapper/map"
  wordpress_mapper_endpoint: "https://k8s-delivery-upp-eu.ft.com/__wordpress-article-mapper/map"
environments: |
    [
      {
        "name":"k8s",
        "read-url": "https://k8s-delivery-upp-eu.ft.com",
        "s3-url": "http://com.ft.imagepublish.k8s.test.s3.amazonaws.com"
      }
    ]
